POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmd4IiwiaWQiOiI2MTFiYWU3NzM1ZTg2NjQ1YmMwNGEyZjQiLCJpYXQiOjE2MjkyMDYzMDV9.iacpj9FSx0hRPcrJbHmaoBbW6rFeQq4ibheOn2lWZgA

{
    "author": "F. Scott Fitzgerald",
    "title": "The Great Gatsby",
    "url": "http://thegreatgatsby.com",
    "likes": 10
}